### ISSUE TITLE
Cannot connect to in image DB, Strange owners of Files

### ISSUE THREAD

**Issue by Dennis123-** [MaksymBilenko/docker-oracle-12c#10]
Hey,

I'm trying to figure out how to start the database, so that all data is cleared when the image stops. However I cannot connect:

docker run -p 8080:8080 -p 1521:1521 -e DBCA_TOTAL_MEMORY=2048 sath89/oracle-12c

Log:
```
ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr
Copying database files
1% complete
3% complete
11% complete
18% complete
26% complete
37% complete
Creating and starting Oracle instance
40% complete
45% complete
50% complete
55% complete
56% complete
60% complete
62% complete
Completing Database Creation
66% complete
70% complete
73% complete
85% complete
96% complete
100% complete
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
Configuring Apex console
Database initialized. Please visit http://#containeer:8080/em http://#containeer:8080/apex for extra configuration if needed
Starting web management console

PL/SQL procedure successfully completed.

Database ready to use. Enjoy! ;)
```
SQLDeveloper test says connection reset after a while. Starting with DB files on Host works except
 the directories will change their owner to a user that's not logged in even though I created them with my user. This is just a little strange the database still works.

**Comment by MaksymBilenko** [comment]
Please check here https://github.com/MaksymBilenko/docker-oracle-12c/issues/3
