### ISSUE TITLE
failed to create symbolic link 

### ISSUE THREAD

**Issue by kherrm** [MaksymBilenko/docker-oracle-12c#100]
Initial run of latest docker-oracle-12c version from 10 days ago Fails with the following error message:

ln: failed to create symbolic link '/u01/app/oracle/product': Permission denied

Docker runs with former versions with the following command worked properly:

docker run -d --name apex -p 8080:8080 -p 1521:1521 -v /volume/docker/apex:/u01/app/oracle -e DBCA_TOTAL_MEMORY=4096 -e sath89/oracle-12c:latest

I did not made any changes in my docker setup. Do you have any idea?

By the way, great work! I really appreciate your efforts.

Cheers,
Kai

**Comment by MaksymBilenko** [comment]
This issue was noticed anly on Centos
More detailed about storage drivers:
https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-for-mac-and-docker-for-windows
