### ISSUE TITLE
security token does not match: you must login again

### ISSUE THREAD

**Issue by anoop9** [MaksymBilenko/docker-oracle-12c#109]
probelm while login to Oracle Enterprise Management console ( http://localhost:8080/em ) . After login with credentials (sys, oracle and as sysdba) I get an error with popup having message : "security token does not match: you must login again"

**Comment by anoop9** [comment]
<img width="1082" alt="screen shot 2018-07-29 at 01 05 33" src="https://user-images.githubusercontent.com/2707378/43361298-b8a19c5c-92cb-11e8-9830-50a55071a513.png">

attached screenshot

**Comment by MaksymBilenko** [comment]
I think that you need to refer to oracle's docs and debug this issue.
Please reopen this issue if it related to this image
