### ISSUE TITLE
when i runing  "docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c " ...

### ISSUE THREAD

**Issue by siyahbeyaz** [MaksymBilenko/docker-oracle-12c#11]
Hi,
docker say that 
"docker: Error response from daemon: Container command '/entrypoint.sh' not found or does not exist.."

**Comment by MaksymBilenko** [comment]
hm, let me check

**Comment by MaksymBilenko** [comment]
Everything works well, I don't see the issue:
https://asciinema.org/a/64eqws5563zlob19clg4t6157
