### ISSUE TITLE
Error starting container with a mapped volume

### ISSUE THREAD

**Issue by tberne** [MaksymBilenko/docker-oracle-12c#116]
Hi. I'm trying to start a container in a Linux box. It fails in both, docker and docker-compose.

Here's my compose configuration:
``` YML
  db_oracle:
    image: sath89/oracle-12c
    ports:
    - 127.0.0.1:1521:1521
    - 127.0.0.1:18080:8080
    volumes:
    - /home/yoda/Documentos/lumis/env/oracle/data:/u01/app/oracle
    environment:
    - DBCA_TOTAL_MEMORY=3072
```
Here's the container output:

```
Database not initialized. Initializing database.
mv: failed to access '/u01/app/oracle/dbs': Too many levels of symbolic links
Starting tnslsnr
Cannot create directory "/u01/app/oracle/cfgtoollogs/dbca".

Unique database identifier check passed.
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2018-09-11_02-14-36-PM (No such file or directory)

/u01/app/oracle/ has enough space. Required space is 6140 MB , available space is 32944 MB.
File Validations Successful.
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2018-09-11_02-14-36-PM (No such file or directory)
Cannot create directory "/u01/app/oracle/cfgtoollogs/dbca/xe".
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2018-09-11_02-14-36-PM (No such file or directory)
Error in file copy from </u01/app/oracle/cfgtoollogs/dbca/silent.log_2018-09-11_02-14-36-PM> to </u01/app/oracle/cfgtoollogs/dbca/xe.log>
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/silent.log_2018-09-11_02-14-36-PM" for further details.
```

When removing the volume mapping, the container starts well.

**Comment by MaksymBilenko** [comment]
Looks like database corruption due to hard stop.

**Comment by MaksymBilenko** [comment]
@jozsefmorrissey Now sure what kind of fix you are looking for.
If you have any suggestion you are welcome to create PR with detailed explanation

**Comment by tberne** [comment]
>           Looks like database corruption due to hard stop.

Actually, it was the very first time the container has been started. So, I don't believe it is something like database corruption due to hard stop, since there was no stop at all.

**Comment by MaksymBilenko** [comment]
Volumes from host might have issues. Try to use docker volumes (non hostPath) like `-v oracle12_data:/u01/app/oracle`

**Comment by tberne** [comment]
@MaksymBilenko, I'll try that later and post the results here.

**Comment by orzeh** [comment]
Using docker volumes in my `docker-compose.yml` solved this issue.

**Comment by siegfriedhuber** [comment]
I could solve the issue with `Cannot create directory` and `Error writing into silent log -` by `chmod -R a+w /home/user1/oracle12-data` 
This is the directory I used when running the docker
```docker run -p 8080:8080 -p 1521:1521 -v /home/user1/oracle12-data:/u01/app/oracle -d sath89/oracle-12c:latest```

**Comment by cn-sy-yl** [comment]
> I could solve the issue with `Cannot create directory` and `Error writing into silent log -` by `chmod -R a+w /home/user1/oracle12-data`
> This is the directory I used when running the docker
> `docker run -p 8080:8080 -p 1521:1521 -v /home/user1/oracle12-data:/u01/app/oracle -d sath89/oracle-12c:latest`

i try this,its helpful
