### ISSUE TITLE
No longer on Docker Hub?

### ISSUE THREAD

**Issue by clphillips** [MaksymBilenko/docker-oracle-12c#128]
I noticed this image is [no longer available on docker hub](https://hub.docker.com/r/sath89/oracle-12c). Any reason why?

**Comment by MaksymBilenko** [comment]
yes, its been deleted, no reason reported from docker hub for now...

**Comment by MaksymBilenko** [comment]
but still you can run docker build from this repo

**Comment by rafael-yure** [comment]
Hi,

I've built the image from this repo, as I wasn't able to download it from docker hub. The image was built as sath89/oracle12c-base, and it doesn't start...

I've tried to do do a simple docker run --name oracle -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c-base and the container starts and then quits. dockers logs oracle returns nothing. Is there anything else I can check? I'm running it on Fedora 29 Server.

**Comment by tgabi333** [comment]
FCUK :(

**Comment by ChaosEngine** [comment]
Any official explanation from `Docker guys` why this happened?

**Comment by marazt** [comment]
Hi. It seems that image `sath89/oracle-12c-base` was removed too. At the end of the file there is command `ADD oracle-12c.tar.gz`. What exactly does this archive contains? 

Thanks

**Comment by marazt** [comment]
> Any official explanation from `Docker guys` why this happened?

 [From another removed Docker repo (Oracle 11g)](https://github.com/wnameless/docker-oracle-xe-11g)

`Since 2019-Feb-13(the Valentine's day eve) this docker image has been removed by DockerHub due to the Docker DMCA Takedown Notice from the Copyright owner which is the Oracle.`

**Comment by delfer** [comment]
I've made copy (docker save & xz) https://delfer.ams3.cdn.digitaloceanspaces.com/sath89_oracle-12c.tar.xz
Download it until I delete this.

**Comment by edpichler** [comment]
> I've made copy (docker save & xz) https://delfer.ams3.cdn.digitaloceanspaces.com/sath89_oracle-12c.tar.xz
> Download it until I delete this.

It's not working. What image is this? I tried it both as base and final.

**Comment by edpichler** [comment]
> Hi. It seems that image `sath89/oracle-12c-base` was removed too. At the end of the file `oracle_base/Dockerfile` there is command `ADD oracle-12c.tar.gz`. What exactly does this archive contains? I would like to be able to build whole image myself.
> 
> Thanks

Have you discovered what is this file? I tried to download the Oracle installer but it does not work. It seems just a compressed oracle home dir, but I am not sure.

**Comment by MaksymBilenko** [comment]
@edpichler The issue is that docker hub doesn't have any swap in builders.
That's why I've made installation from oracle installer manually and then compressed installed oracle home dir into oracle-12c.tar.gz file...
I think that if we would use bitbucket we would be able to make this fully automated build.

**Comment by edpichler** [comment]
> @edpichler The issue is that docker hub doesn't have any swap in builders.
> That's why I've made installation from oracle installer manually and then compressed installed oracle home dir into oracle-12c.tar.gz file...
> I think that if we would use bitbucket we would be able to make this fully automated build.

Got it, it's a fully compressed home dir! Haven't you uploaded it in some place? I tried to create one but did not worked.

**Comment by MaksymBilenko** [comment]
Also having issues with tnslsnr.... 
I'll update this thread if I would have a chance to make it work

**Comment by MaksymBilenko** [comment]
@delfer May I ask you to export this with layers info 
```IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
ee3351d51185        8 months ago        /bin/sh -c #(nop)  CMD [""]                     0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  ENTRYPOINT ["/entrypoint.…   0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  VOLUME [/docker-entrypoin…   0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  EXPOSE 8080                  0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  EXPOSE 1521                  0B                  
<missing>           8 months ago        /bin/sh -c apt-get update && apt-get -y inst…   11.3MB              
<missing>           8 months ago        /bin/sh -c #(nop) ADD file:0dbb290587db286f5…   5.09kB              
<missing>           8 months ago        /bin/sh -c #(nop)  ENV USE_UTF8_IF_CHARSET_E…   0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  ENV PATH=/usr/local/sbin:…   0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  ENV DBCA_TOTAL_MEMORY=2048   0B                  
<missing>           8 months ago        /bin/sh -c #(nop)  ENV WEB_CONSOLE=true         0B                  
<missing>           3 years ago         /bin/sh -c #(nop) ADD file:f4dfef572d9518714…   5.5GB               
<missing>           3 years ago         /bin/sh -c groupadd --gid 1001 dba && userad…   334kB               
<missing>           3 years ago         /bin/sh -c ln -s /usr/bin/awk /bin/awk          12B                 
<missing>           3 years ago         /bin/sh -c apt-get update && apt-get install…   946kB               
<missing>           3 years ago         /bin/sh -c #(nop) ENV ORACLE_SID=xe             0B                  
<missing>           3 years ago         /bin/sh -c #(nop) ENV ORACLE_HOME=/u01/app/o…   0B                  
<missing>           3 years ago         /bin/sh -c #(nop) ENV DEBIAN_FRONTEND=nonint…   0B                  
<missing>           3 years ago         /bin/sh -c #(nop) MAINTAINER Maksym Bilenko …   0B                  
<missing>           3 years ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0B                  
<missing>           3 years ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$…   1.9kB               
<missing>           3 years ago         /bin/sh -c echo '#!/bin/sh' > /usr/sbin/poli…   195kB               
<missing>           3 years ago         /bin/sh -c #(nop) ADD file:531ac3e55db4293b8…   188MB ```

Or maybe you would be able to restore base image?

**Comment by MaksymBilenko** [comment]
Database available at 
quay.io/maksymbilenko/oracle-12c:latest
quay.io/maksymbilenko/oracle-12c:novnc
This is SE2
