### ISSUE TITLE
Startup container error

### ISSUE THREAD

**Issue by rastafiz** [MaksymBilenko/docker-oracle-12c#13]
Hi. I tried to run this image and had error in /u01/app/oracle/cfgtoollogs/dbca/xe.log

>Unique database identifier check passed.

>/u01/app/oracle/ does not have enough space. Required space is 1580 MB , available space is 0 MB.

I run this command:

>docker run --name local_oracle_12 -d -p 8090:8080 -p 1521:1521 -v /my/oracle/data:/u01/app/oracle sath89/oracle-12c

What did I do wrong?

**Comment by MaksymBilenko** [comment]
I believe that this piece of log is showing the issue:
`Required space is 1580 MB , available space is 0 MB.`

**Comment by rastafiz** [comment]
I see what you mean, but the folder where I mount the folder /u01/app/oracle has enough space. If I run the container without mounting volume it runs successfully. 

And I have one more problem. I can't enable in-memory acceleration. Did you try to enable this mode?

1. I set up parameters:
>ALTER SYSTEM SET SGA_TARGET=3G SCOPE=SPFILE;
>ALTER SYSTEM SET INMEMORY_SIZE=2G SCOPE=SPFILE;

2. restart container
3. check parameters, all parameters are ok
> SHOW PARAMETER INMEMORY

4. Try to alter my tablespace
>ALTER TABLESPACE mytablespace DEFAULT INMEMORY;

and have error message like:
ora-00439 feature not enabled: In-Memory Column Store

**Comment by variantf** [comment]
@rastafiz I have the same problem that it still says ```ora-00439 feature not enabled: In-Memory Column Store``` after I set inmemory_size. did you solve this problem?

@MaksymBilenko any ideas?

**Comment by MaksymBilenko** [comment]
Assuming this asnswer http://www.dba-oracle.com/t_ora_00439_feature_not_enabled_string.htm
You nee dto use Enterprise Edition for this:
https://github.com/MaksymBilenko/docker-oracle-ee-12c
https://hub.docker.com/r/sath89/oracle-ee-12c/

**Comment by variantf** [comment]
Thank you @MaksymBilenko
