### ISSUE TITLE
Pulling an (quay.io/maksymbilenko/oracle-12c) image in Github actions CI gives an error v2 Schema 1support removed

### ISSUE THREAD

**Issue by AnushaErrabelli** [MaksymBilenko/docker-oracle-12c#137]
Error details:

[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.
##[error]Process completed with exit code 1.

**Comment by AnushaErrabelli** [comment]
Advance thank you for checking this issue

**Comment by MaksymBilenko** [comment]
Looks like issue from your side
quay.io docker pull works fine and auto-builds aswell

**Comment by AnushaErrabelli** [comment]
Yes, thank you for your reply on it! I fixed the issue but I was not able to establish the connection between api and db using Docker running on local environment. If you have any information can you please share?  Thank you for helping!

**Comment by AnushaErrabelli** [comment]
I'm seeing this error "{
  "Status": 500,
  "Error": "InternalServerError",
  "Message": "Network Transport: TCP transport address connect failure"
}"

**Comment by MaksymBilenko** [comment]
Seems like issue from your end, I'm able to pull
