### ISSUE TITLE
Insufficient Free Space issue

### ISSUE THREAD

**Issue by AG-Labs** [MaksymBilenko/docker-oracle-12c#139]
When starting (even on a new machine) it complains that there is not enough space by around 20MB. Other answers state that changing the /etc/sysconfig/docker-storage file to container `DOCKER_STORAGE_OPTIONS= --storage-opt dm.basesize=20G`

I can not seem to get this container started at all, yet no one seems to have the same issue here.

**Comment by mcsql0** [comment]
Me too, I don't know if you have solved it

**Comment by AG-Labs** [comment]
I believe another member in my team fixed this. I will check our old docs tomorrow see what I can find

> Me too, I don't know if you have solved it
