### ISSUE TITLE
Not sufficient memory for oracle

### ISSUE THREAD

**Issue by AKASHISH011** [MaksymBilenko/docker-oracle-12c#140]
Hello Sir, I m  new in Docker and trying to install oracle 12c in docker. but it got failed after 3%. 
I am using docker desktop version 2.2.0.3 in Window 10 with window's container in D:/Docker_WS directory.

below are the warnings - 
[WARNING] [DBT-11209] Current available physical memory is less than the required physical memory (2,048MB) for creating the database.
[WARNING] [DBT-11217] Unable to check available shared memory on specified node(s) (699630acd0fc).

Copying database files
1% complete
2% complete
3% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
found files in /u01/app/oracle/oradata Using them instead of initial database
ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/u01/app/oracle/product/12.2.0/SE/dbs/initxe.ora'
Starting web management console
BEGIN DBMS_XDB.sethttpport(8080); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0
[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable
Database ready to use. Enjoy! ;)
ERROR:
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Additional information: 3701
Additional information: 1802802571..

I am not getting this. Please help me to setup this. If this is realted to Docker VM then plese explain it in details that how can i resolve the issues. after installation i wanna to import backup file in this.

**Comment by MaksymBilenko** [comment]
Fixed with DBCA_TOTAL_MEMORY=4096 and 4096 is set as default
