### ISSUE TITLE
APEX is not operating

### ISSUE THREAD

**Issue by ka84** [MaksymBilenko/docker-oracle-12c#147]
1) Started container with port mapping (-p 8080:8080).
2) Waited until db is created and everything is up  & running
3) Open a browser on my host machine and follow http://localhost:8080/apex
4) Browser redirects to [http://localhost:8080/apex/apex] (adds another /apex/ to the end) and says:

Not found
The requested URL /apex/apex was not found on this server

**Comment by MaksymBilenko** [comment]
Known issue, fixes on Apex update via https://github.com/MaksymBilenko/docker-oracle-apex
For now I don't know why it doesn't work from image

**Comment by LaurentOrban4Collibra** [comment]
$ docker pull sath89/apex
Using default tag: latest
Error response from daemon: pull access denied for sath89/apex, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Blackfish:~ laurent$

**Comment by JohnLongSilver** [comment]
$ docker pull sath89/apex
Using default tag: latest
Error response from daemon: pull access denied for sath89/apex, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
$

**Comment by MaksymBilenko** [comment]
Apex moved to quay.io
