### ISSUE TITLE
How can I use DBCA in that docker?

### ISSUE THREAD

**Issue by jradesenv** [MaksymBilenko/docker-oracle-12c#15]
I have to use DBCA to execute some templates. How can I use it with this docker container?

**Comment by ChaosEngine** [comment]
Well, one could use vnc docker inherited from docker-oracle-12c and start xterm session from that.
I've been testing small enhancement exactly for this purpose: https://github.com/ChaosEngine/dockerfiles/tree/master/oracle12c
