### ISSUE TITLE
DBCA operation failed... not sure why, can't seem to view the log :(

### ISSUE THREAD

**Issue by s50600822** [MaksymBilenko/docker-oracle-12c#16]
```
s5060@DESKTOP-8VTHH4M MINGW64 ~
$ docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c
09179912ff6e6e08226e9e571415994e2ed60fe7cdc58c0d6b52ee87f0b6fd33

s5060@DESKTOP-8VTHH4M MINGW64 ~
$ docker logs -f 09179912ff6e6e08226e9e571415994e2ed60fe7cdc58c0d6b52ee87f0b6fd33
ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr
Copying database files
1% complete
2% complete
4% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.

s5060@DESKTOP-8VTHH4M MINGW64 ~
$ less /u01/app/oracle/cfgtoollogs/dbca/xe/xe.log
/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log: No such file or directory

s5060@DESKTOP-8VTHH4M MINGW64 ~
```

**Comment by ansgarkroger** [comment]
got the same issue.
copied the log file over using:
`docker cp mydockercontainername:/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log .`

It shows:
```
 The specified shared pool size or SGA size "292MB" does not meet the recommended minimum size requirement "331MB". This will make database creation fail. Do you want to continue?

Unique database identifier check passed.

/u01/app/oracle/ has enough space. Required space is 6140 MB , available space is 53851 MB.
File Validations Successful.
Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 2%
ORA-00821: Specified value of sga_target 292M is too small, needs to be at least 364M
ORA-01078: failure in processing system parameters

DBCA_PROGRESS : 4%
ORA-01034: ORACLE not available

ORA-01034: ORACLE not available

DBCA_PROGRESS : DBCA Operation failed.
```

my problem is that I have difficulties investigating further. when I run 
`docker exec -it a70e80d41c5e sh`
I get
`rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"`

**Comment by MaksymBilenko** [comment]
It should be fixed already

**Comment by nouhouari** [comment]
Facing same issue today. What is the fix ?

**Comment by ppapaj** [comment]
I solved the problem simply by adding RAM to Docker VM. I increased it from 1024M to 2048M.

**Comment by geeeeeeeeek** [comment]
@MaksymBilenko This is a common issue building your image. @ppapaj 's answer is exactly to the point and I think you should put it into your README to highlight the issue.

Quick commands:
```
docker-machine stop
VBoxManage modifyvm default --memory 4096
docker-machine start
```

**Comment by MaksymBilenko** [comment]
Thank you guys,
I've added link to this issue at the README.md
Cheers

**Comment by stavrosicsd** [comment]
When I try to run in swarm mode (i.e. docker service create) I get the same error message.

**Comment by AKASHISH011** [comment]
> @MaksymBilenko This is a common issue when building your image. @ppapaj 's answer is exactly to the point and I think you should put it into your README to highlight the issue.
> 
> Quick commands:
> 
> ```
> docker-machine stop
> VBoxManage modifyvm default --memory 4096
> docker-machine start
> ```

not working this command. 'docker-machine' is not recognized as an internal or external command,
operable program or batch file.

**Comment by raobhoopathi1990** [comment]
would you please give me exact commands to stop and run machine and how to increase the memory to 4096 iam working on aws instance

**Comment by insu0929** [comment]
> @MaksymBilenko This is a common issue when building your image. @ppapaj 's answer is exactly to the point and I think you should put it into your README to highlight the issue.
> 
> Quick commands:
> 
> ```
> docker-machine stop
> VBoxManage modifyvm default --memory 4096
> docker-machine start
> ```

for those of you who cannot run the command, just simply open your oracle vm virtual box, and change the settings of the container. (mainboard memory -> 4096MB)
