### ISSUE TITLE
ORA-29275:partial multibyte character

### ISSUE THREAD

**Issue by wtujvk** [MaksymBilenko/docker-oracle-12c#161]
Use the command:
`docker run -d --name myoracle  -p 8080:8080 -p 1521:1521 -v /my/oracle/data:/u01/app/oracle -e ORACLE_ALLOW_REMOTE=true -e ORACLE_CHARACTERSET=al32utf8 -e DBCA_TOTAL_MEMORY=2048 quay.io/maksymbilenko/oracle-12c`

And when It has Chinese characters,  It call 'ORA-29275:partial multibyte character'
The  client is Navicat15.0.11,  oracle server in  Centos7+docker.

![image](https://user-images.githubusercontent.com/17868266/154233500-d7121acb-c15a-43ea-96ed-bd0d78fbd10c.png)

Use this command 
`docker run -d -p 1521:1521 --name oracle11g registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g`， 
It Ok, but oracle_11g are not supported Table names with 30 characters. 

-----------------------------------------------------------------------
使用docker命令行启动oracle-12c, 可以创建容器。
但是有的表查询会报错。本地window10, 服务器centos7+docker+quay.io/maksymbilenko/oracle-12c
网上查询资料说是编码问题，但是设置了还是无效。
使用oracle-11c可以安装成功，不会报这个错， 但是oracle-11不支持表名超过30个字符。

**Comment by MaksymBilenko** [comment]
Try to set $CHARACTER_SET env variable
Detailed configuration you could check here:
https://github.com/MaksymBilenko/docker-oracle-12c/blob/master/entrypoint.sh#L17

**Comment by wtujvk** [comment]
![image](https://user-images.githubusercontent.com/17868266/154718101-a881e39c-2b0c-474f-b59f-bdd8c9471433.png)
