### ISSUE TITLE
Permission denied  

### ISSUE THREAD

**Issue by nouhouari** [MaksymBilenko/docker-oracle-12c#18]
Hi,

I'm trying to run the image on MacOsX.
Docker is running on VirtualBox VM.
I share the /User directory between VirtualBox and my MacBook.
I've created a oracleData directory and grant all permissions.

I run the docker image using this command :

> docker run -p "1521:1521" -p "8686:8080" -v /Users/xxxxx/Documents/oracleData:/u01/app/oracle sath89/oracle-12c

I get this error.

ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr
Cannot create directory "/u01/app/oracle/cfgtoollogs/dbca".
Database Configuration Assistant failed to detect options for this Oracle Installation. 
/u01/app/oracle/product/12.1.0/xe/dbs/initDBUA5224665.ora (Permission denied)
Due to this failure some Database Configuration Assistant features will not be available. Do you want to continue?
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM (No such file or directory)
The specified shared pool size or SGA size "297MB" does not meet the recommended minimum size requirement "331MB". This will make database creation fail. Do you want to continue?
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM (No such file or directory)

Unique database identifier check passed.
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM (No such file or directory)

/u01/app/oracle/ has enough space. Required space is 6140 MB , available space is 115447 MB.
File Validations Successful.
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM (No such file or directory)
Cannot create directory "/u01/app/oracle/cfgtoollogs/dbca/xe".
Error writing into silent log -- /u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM (No such file or directory)
Error in file copy from </u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM> to </u01/app/oracle/cfgtoollogs/dbca/xe.log>
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/silent.log_2016-07-30_10-52-24-AM" for further details.

**Comment by MaksymBilenko** [comment]
Hi @nouhouari,
There is always an issues with data volumes and VirtualBox.
Currently I'm using Docker for Mac that doesn't use VirtualBox and everything works well.
