### ISSUE TITLE
/u01/app/oracle/product/12.1.0/xe/dbs/initxe.ora: No such file or directory

### ISSUE THREAD

**Issue by dockerlet** [MaksymBilenko/docker-oracle-12c#19]
LRM-00109: could not open parameter file '/u01/app/oracle/product/12.1.0/xe/dbs/initxe.ora' 

cat: /u01/app/oracle/product/12.1.0/xe/dbs/initxe.ora: No such file or directory

**Comment by MaksymBilenko** [comment]
@dockerlet Try to wipe out database files and reinit database
