### ISSUE TITLE
Adding data volume with Docker for Windows

### ISSUE THREAD

**Issue by kvarv** [MaksymBilenko/docker-oracle-12c#20]
I'm trying to run
` docker run -d -p 8080:8080 -p 1521:1521 -v /c/tmp/ora:/u01/app/oracle sath89/oracle-12c
`
on Windows 10 with Docker for Windows.

`ln: failed to create symbolic link '/u01/app/oracle/product': Operation not supported`

Any ideas?

Thank you!

**Comment by MaksymBilenko** [comment]
There is an issues with NTFS file systems. This is related to Docker itself but not this image,
Please read this: https://github.com/docker/docker/issues/2259

**Comment by dronlinux** [comment]
Приветствую. То есть нельзя воспользоваться образом в ОС Windows 7/10, если запускать с параметром -v ?

**Comment by MaksymBilenko** [comment]
Привет,
Можно, но используя волюм виртуальной машины, к примеру так:
`-v oracle_data:/u01/app/oracle`
в таком случае `oracle_data`  возможно будет переиспользовать, но файлы базы не будут на ФС хоста, а в виртуальной машине docker

**Comment by dronlinux** [comment]
Спасибо, за помощь! Все заработало.
