### ISSUE TITLE
Database initialization

### ISSUE THREAD

**Issue by wagner-wutzke** [MaksymBilenko/docker-oracle-12c#22]
Hi Maksym.
Thanks for sharing your work!
Do you think that this would be adding a database initialization feature to the image?

`# Dockerfile
FROM wnameless/oracle-xe-11g

ADD init.sql /docker-entrypoint-initdb.d/`

I did find it here: https://github.com/wnameless/docker-oracle-xe-11g
Thanks you.
Cheers,

Wagner

**Comment by MaksymBilenko** [comment]
Yeah, it could be added. I'll try to do this today

**Comment by MaksymBilenko** [comment]
@wagner-wutzke, Done, please take a look and update with any issues

**Comment by wagner-wutzke** [comment]
Works perfectly. Great job. Thanks a lot!
