### ISSUE TITLE
[Question] How to run sqlplus with Docker for macOS?

### ISSUE THREAD

**Issue by donhuvy** [MaksymBilenko/docker-oracle-12c#25]
I try command
```
sqlplus system/oracle@//localhost:1521/xe.oracle.docker
```
The result:
```
Last login: Sun Jan  8 14:40:32 on ttys002
➜  ~ env|grep ORACLE_SID
➜  ~ 
➜  ~ exec bash
bash-3.2$ env | grep ORACLE_SID
bash-3.2$ sqlplus system/oracle@//localhost:1521/xe.oracle.docker
bash: sqlplus: command not found
bash-3.2$ 
```

**Comment by MaksymBilenko** [comment]
@donhuvy,
`$ORACLE_HOME/bin/sqlplus system/oracle@//localhost:1521/xe.oracle.docker`
I'll add sqlplus to the PATH

**Comment by ukreddy-erwin** [comment]
This docker file not working.


FROM sath89/oracle-12c
EXPOSE 1521
EXPOSE 8080
#RUN apt update
#RUN apt install nano
RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/app
COPY MappingManager_Oracle.sql /usr/src/app/MappingManager_Oracle.sql
RUN $ORACLE_HOME/bin/sqlplus  system/oracle@//localhost:1521/xe @/usr/src/app/MappingManager_Oracle.sql

Getting error as /bin/sh: 1: /u01/app/oracle/product/12.1.0/xe/bin/sqlplus: not found
