### ISSUE TITLE
Extremely slow to start on MacBook pro

### ISSUE THREAD

**Issue by viciss** [MaksymBilenko/docker-oracle-12c#26]
My docker version is as below:
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

I start oracle docker image with following command:
docker run --name oracle -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c

And it takes about 10 minutes to still in the "starting tnslsnr" line for the first time running:
ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr

Anyone knows why this happens? I can start for first time on centos within 10 minutes.

**Comment by MaksymBilenko** [comment]
@viciss I'm running on my MBP early 2013, and it takes about 3-5 minutes to init database...
