### ISSUE TITLE
mv: cannot remove

### ISSUE THREAD

**Issue by boernd** [MaksymBilenko/docker-oracle-12c#27]
Getting the following error starting the container:

```
> docker logs bf6965fa6896322d3b29863730464203865792dba20ceb5d27504b611b002f72
ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
mv: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty
```

**Comment by MaksymBilenko** [comment]
@boernd,
That's strange, could you please provide some more details

**Comment by Nunalves** [comment]
same here, just doing 'docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c'
after a fresh docker install

**Comment by loskov** [comment]
@MaksymBilenko 
Same problem for me. System details:
`Docker version 1.12.5, build 7392c3b`
`CentOS Linux release 7.3.1611 (Core)`

What I've done:
`$ docker pull sath89/oracle-12c`
`$ docker run --rm -P sath89/oracle-12c`
`ls: cannot access /u01/app/oracle/oradata: No such file or directory`
`Database not initialized. Initializing database.`
`mv: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty`

If you need anything else - let me know.

**Comment by MaksymBilenko** [comment]
@loskov That's odd. I'm not having this kind of issues.

**Comment by MaksymBilenko** [comment]
Try to run with `-it` flag. This might fix the issue

**Comment by loskov** [comment]
Nothing changed.
Ran it all combinations: interactive and non-interactive + detached and attached.
Always the same output.

**Comment by kstobbel** [comment]
Same over here :( 
```
Docker version: 1.13.1
CentOS Linux release 7.3.1611 (Core)
```

Running with `-it` flag does not help.

**Comment by MaksymBilenko** [comment]
That's very odd... Ok I'll merge PR, and lets see if that helps...

**Comment by MaksymBilenko** [comment]
@boernd @Nunalves @loskov @kstobbel  Could you please pull and confirm that issue was fixed?
Cheers

**Comment by loskov** [comment]
Works for me! Thanks!

**Comment by MaksymBilenko** [comment]
@kstobbel I've rolled back you commit and I've just ignored errors from `mv` command.

**Comment by lukastoledo** [comment]
Same problem here... =/
`Starting docker_oracle_1
Attaching to docker_oracle_1
oracle_1  | rm: cannot remove '/u01/app/oracle/product': Is a directory
docker_oracle_1 exited with code 1
`

**Comment by MaksymBilenko** [comment]
Looks like Docker at Centos issue.
I had similar issue that was fixed by changig default storage driver of docker.
Issue is that docker container unable to modify image's files.

**Comment by MaksymBilenko** [comment]
This issue was noticed anly on Centos
More detailed about storage drivers:
https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-for-mac-and-docker-for-windows
