### ISSUE TITLE
How to connect using sqlplus?

### ISSUE THREAD

**Issue by Envek** [MaksymBilenko/docker-oracle-12c#3]
Hello! Thank you for this image!

Can't connect to it using `sqlplus` command.

Launched container with:

```sh
sudo docker run -d -p 8080:8080 -p 1521:1521 -v ~/project/oracle-data:/u01/app/oracle sath89/oracle-12c
```

Trying to do:

```sh
sqlplus system/oracle@localhost:1521/xe
```

Getting:

```
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor.
```

Also trying via DBeaver GUI:

![2015-12-21 10-44-49](https://cloud.githubusercontent.com/assets/264400/11925770/ea6cfb4e-a7cf-11e5-9eac-45c96274351d.png)

If I go to <http://localhost:8080/> I will get `ERR_CONNECTION_RESET`.

Ports are listening:

```sh
$ sudo netstat -nltp                                                                                                                                                      
tcp6       0      0 :::8080                 :::*                    LISTEN      5719/docker-proxy
tcp6       0      0 :::1521                 :::*                    LISTEN      5727/docker-proxy
```

Container is running:
```
sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                            NAMES
56a5acf64004        sath89/oracle-12c   "/entrypoint.sh "   17 minutes ago      Up 17 minutes       0.0.0.0:1521->1521/tcp, 0.0.0.0:8080->8080/tcp   gloomy_poitras
```

Ubuntu 15.10 x64, freshly installed Docker 1.9.1.

Any other information I can provide to resolve it?

**Comment by MaksymBilenko** [comment]
Is there any errors in docker container? Could you please send me the logs
Thank you

**Comment by MaksymBilenko** [comment]
Database initialization might take 2-10 minutes. Seems like you was trying to connect before Database finished initialization

**Comment by MaksymBilenko** [comment]
Closed due no response

**Comment by bbenning** [comment]
Had a similar problem connecting via sqlplus. What screwed with my mind is that the sid and service name aren't the same in this image. I was able to log on using the service name like so: 

$ sqlplus system/oracle@//localhost:1521/xe.oracle.docker

**Comment by MaksymBilenko** [comment]
I think that you just need to wait for data init at the start...

**Comment by swy680614** [comment]
Hi, Thank you for your image.
I can't connect oracle 12c via sqlplus.
Here is the error message.
![2016-01-27 11 01 36](https://cloud.githubusercontent.com/assets/8295029/12602650/ee0bd7d8-c4e5-11e5-87a6-061c8e5a7762.png)

**Comment by MaksymBilenko** [comment]
@swy680614 Could you please show me the logs of this container?

**Comment by bbenning** [comment]
swy680614 seems to have a typo in localhost. It's typed there "loaclhost", not sure if that's in his hostfile or something?!

Anyway, as from my command line (running within a docker-machine @ port 49161):

---
`$ docker ps`
`CONTAINER ID        IMAGE                                                                                 COMMAND              CREATED             STATUS              PORTS                                                                NAMES`
`286526178c21        sath89/oracle-12c                                                                     "/entrypoint.sh "    2 days ago          Up 2 days           8080/tcp, 0.0.0.0:49161->1521/tcp   `

---
$ docker logs 2865
ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr
Copying database files
1% complete
3% complete
11% complete
18% complete
37% complete
Creating and starting Oracle instance
40% complete
45% complete
50% complete
55% complete
56% complete
60% complete
62% complete
Completing Database Creation
66% complete
70% complete
73% complete
85% complete
96% complete
100% complete
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
Configuring Apex console
Database initialized. Please visit http://#containeer:8080/em http://#containeer:8080/apex for extra configuration if needed
Disabling web management console

PL/SQL procedure successfully completed.

Database ready to use. Enjoy! ;)

---
$ sqlplus system/oracle@192.168.99.100:49161/xe

SQL*Plus: Release 11.2.0.4.0 Production on Thu Jan 28 11:43:24 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor


Enter user-name: 

---
$ sqlplus system/oracle@//192.168.99.100:49161/xe.oracle.docker

SQL*Plus: Release 11.2.0.4.0 Production on Thu Jan 28 11:45:32 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

SQL> 

---
$ docker exec -ti 2865 bash
root@286526178c21:/# tail /u01/app/oracle/cfgtoollogs/dbca/xe/xe.log
DBCA_PROGRESS : 70%
DBCA_PROGRESS : 73%
DBCA_PROGRESS : 85%
DBCA_PROGRESS : 96%
DBCA_PROGRESS : 100%
Database creation complete. For details check the logfiles at:
 /u01/app/oracle/cfgtoollogs/dbca/xe.
Database Information:
Global Database Name:xe.oracle.docker
System Identifier(SID):xe

---
A tail on /u01/app/oracle/diag/tnslsnr/286526178c21/listener/trace/listener.log gives:
28-JAN-2016 10:43:24 * (CONNECT_DATA=(SERVICE_NAME=xe)(CID=(PROGRAM=sqlplus)(HOST=Myhost.local)(USER=myuser))) * (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.99.1)(PORT=62461)) * establish * xe * 12514
TNS-12514: TNS:listener does not currently know of service requested in connect descriptor
28-JAN-2016 10:45:32 * (CONNECT_DATA=(SERVICE_NAME=xe.oracle.docker)(CID=(PROGRAM=sqlplus)(HOST=Myhost.local)(USER=myuser))) * (ADDRESS=(PROTOCOL=tcp)(HOST=192.168.99.1)(PORT=62472)) * establish * xe.oracle.docker * 0

**Comment by MaksymBilenko** [comment]
@bbenning @swy680614 I'll take a look at this issue when I'll have time for this.
Hopefully I'll take a look at end of this week.
Cheers

**Comment by swy680614** [comment]
Here is my error log.
![2016-01-28 6 55 44](https://cloud.githubusercontent.com/assets/8295029/12642519/3e1209c6-c5f1-11e5-883f-7b8f05aef85d.png)

**Comment by MaksymBilenko** [comment]
@swy680614 
Seems like you have corrupted database files,
Cleanup database files at the host and then start again

**Comment by swy680614** [comment]
How to cleanup database files ?

**Comment by MaksymBilenko** [comment]
@swy680614 if you ware starting container with -v /my/oracle/data:/u01/app/oracle
Then you need to delete /my/oracle/data
If not - then just delete container and start new one

**Comment by Odin8448** [comment]
bbenning  is right.
type the right service name in tnsnames.ora of your client instalation.
whished i saw that post 1 day ago, would have saved me so much time.

**Comment by drewwells** [comment]
Wish this was in the readme, lost a day trying to diagnose ORA-12514 errors.

**Comment by tkvinfolio** [comment]
I created a new user/schema assigning it a separate table space as:

> create user eportal_adm  IDENTIFIED BY <password> default tablespace eportal_adm_tabspace 
>          temporary tablespace eportal_adm_temp_tabspace;
> grant create session to eportal_adm;
> grant create table to eportal_adm;
> grant unlimited tablespace to eportal_adm;

### Question:  
**How can I make the listener to listen to this new SID eportal_adm?**

> There is no listener.ora but there is $ORACLE_HOME/xe/network/admin/samples/listener.ora
> Lsnrctl command shows it is listening to port 1521 with  "xe.oracle.docker" service

> LSNRCTL> status
> Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
> STATUS of the LISTENER
> ------------------------
> Alias                     LISTENER
> Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
> Start Date                31-JUL-2016 06:24:16
> Uptime                    0 days 0 hr. 54 min. 7 sec
> Trace Level               off
> Security                  ON: Local OS Authentication
> SNMP                      OFF
> Listener Log File         /u01/app/oracle/diag/tnslsnr/8c7c5ad0f4f6/listener/alert/log.xml
> Listening Endpoints Summary...
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=8c7c5ad0f4f6)(PORT=1521)))
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=8c7c5ad0f4f6)(PORT=8080))(Presentation=HTTP)(Session=RAW))
> Services Summary...
> Service "xe.oracle.docker" has 1 instance(s).
> .....

THANKS  a BUNCH.

Sammy

**Comment by x343734282** [comment]
hi , thank you for your image.
I also can not connect db server with sqlplus.
![error](https://user-images.githubusercontent.com/799766/37392822-3904d338-27aa-11e8-81e2-6cf21a681d26.png)

There are some warns in the oracle container console , as below image.  thanks a lot.
![error1](https://user-images.githubusercontent.com/799766/37392987-c431fc7e-27aa-11e8-966f-d80930ead731.png)

**Comment by MaksymBilenko** [comment]
@tkvinfolio you can run dbca manually
Check out noVNC branch
```
docker run -d -p 8080:8080 -p 1521:1521 -p 6800:6800 -e MANUAL_DBCA=true -e VNC_PASSWORD=passwd sath89/oracle-12c
#Default VNC_PASSWORD=oracle
#Open in Browser http://localhost:6800/vnc_auto.html
```
