### ISSUE TITLE
Error when starting container Specified value of sga_target 768M is too small, needs to be at least 1096M

### ISSUE THREAD

**Issue by maduma** [MaksymBilenko/docker-oracle-12c#31]
/u01/app/oracle/ has enough space. Required space is 6140 MB , available space is 28684 MB.
File Validations Successful.
Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 2%
ORA-00821: Specified value of sga_target 768M is too small, needs to be at least 1096M
ORA-01078: failure in processing system parameters

**Comment by MaksymBilenko** [comment]
Try to set `-e DBCA_TOTAL_MEMORY=2048`

2017-03-24 10:01 GMT+02:00 maduma <notifications@github.com>:

**Comment by maduma** [comment]
It looks better. Thanks for help was fast :-)
Sorry i did not check the documentation carefully !
