### ISSUE TITLE
error while creating a container

### ISSUE THREAD

**Issue by alpoor** [MaksymBilenko/docker-oracle-12c#32]
$ docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c
51d56f3c691c2f20a80c889eaa08053042f0344d7eabf1493903ee01dbc74a04
[user@alpoor1 dbs]$ docker logs -f 51d56f3c691c2f20a80c889eaa08053042f0344d7eabf1493903ee01dbc74a04
Database not initialized. Initializing database.
ls: cannot access /u01/app/oracle/oradata: No such file or directory
mv: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty
Starting tnslsnr
Copying database files
1% complete
2% complete
4% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
[user@alpoor1 dbs]$

**Comment by dasqc** [comment]
for me the same.
Enviroment: Kitmatic on Windows 10

**Comment by MaksymBilenko** [comment]
Any more details? `/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log` ?

**Comment by alpoor** [comment]
I can't get to that log file for details since it exits from container as soon as I get the error

**Comment by dasqc** [comment]
The specified shared pool size or SGA size "297MB" does not meet the recommended minimum size requirement "331MB". This
will make database creation fail. Do you want to continue?

Unique database identifier check passed.

/u01/app/oracle/ has enough space. Required space is 6140 MB , available space is 10121 MB.
File Validations Successful.
Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 2%
ORA-00821: Specified value of sga_target 300M is too small, needs to be at least 364M
ORA-01078: failure in processing system parameters

DBCA_PROGRESS : 4%
ORA-01034: ORACLE not available

ORA-01034: ORACLE not available

DBCA_PROGRESS : DBCA Operation failed.

**Comment by dasqc** [comment]
increased memory of VM from 1024 to 2048MB works!

**Comment by MaksymBilenko** [comment]
Just commited default memory at entrypoint up to 2048. https://github.com/MaksymBilenko/docker-oracle-12c/commit/ff07a05bd53375adfd788a8210a7053f9c5c8df1
