### ISSUE TITLE
Failure when restarting container

### ISSUE THREAD

**Issue by eduardotang** [MaksymBilenko/docker-oracle-12c#35]
found files in /u01/app/oracle/oradata Using them instead of initial database
ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/u01/app/oracle/product/12.1.0/xe/dbs/initxe.ora'
Starting web management console
BEGIN DBMS_XDB.sethttpport(8080); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)

**Comment by MaksymBilenko** [comment]
@eduardotang Maybe you were restarting container not graceful or before it was fully initialized?
