### ISSUE TITLE
Cannot start comitted image. Varchar to 32k?

### ISSUE THREAD

**Issue by Dennis123-** [MaksymBilenko/docker-oracle-12c#38]
Hey,

I actually got two issues which are more questions then actual bugs here.

1. If I start the db (without local files) the files are in the container which is fine as its just a portable testing db. If i start the comitted image again it says: 
`ls: cannot access /u01/app/oracle/oradata: No such file or directory
Database not initialized. Initializing database.
Starting tnslsnr
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe.log" for further details.`
Restarting the stopped container works though. Why does it try to reinit the db?

2. Oracle 12c has support for varchars > 4k which I would like to use. The problem is the database has to be restartet in migration mode. Is it possible to hook this in somewhere in the init? `MAX_STRING_SIZE=extended`

**Comment by albfan** [comment]
This should be solved after remove the volume

**Comment by MaksymBilenko** [comment]
Already re-builded without VOLUME,
Could you please test it now

**Comment by Dennis123-** [comment]
@albfan 
Thanks for the suggestion will do so next time. Seemed more like support questions than actual problems.
@MaksymBilenko 
I can commit and restart the image with the data in the image. Thats good :)

About the second issue I will try to fight my way through the documentation to find it.

**Comment by MaksymBilenko** [comment]
@Dennis123- If you would find some handy information that missing at README - please update it.
Thanks

**Comment by Dennis123-** [comment]
According to this: https://oracle-base.com/articles/12c/extended-data-types-12cR1
It seems you have to init the DB, restart it in update mode, set values and restart again. I think this should be done on first creation?

**Comment by albfan** [comment]
If you add a .sql on docker init volume it will execute that. If shutdown causes problems, you can mimic impdb here doc function.

Anyway you can always do that yourself and import dump later TMTOWTDI
