### ISSUE TITLE
define charset can cause troubles with length

### ISSUE THREAD

**Issue by albfan** [MaksymBilenko/docker-oracle-12c#42]
Removing `NLS_LANG=.$CHARACTER_SET` in impdp succesfully loads a dump. Do you want a PR to allow to disable those sets?

something like `-e DEFAULT_CHARSET=false` or whatever that works for you

**Comment by albfan** [comment]
This is a possible implemetation

https://github.com/albfan/docker-oracle-12c/commit/3ee5f8028287d3b411e78a0616d65b9f01fd345b

with `-e USE_UTF8_IF_CHARSET_EMPTY=true` you will use "AL32UTF8" if none defined

**Comment by MaksymBilenko** [comment]
@albfan Could you please create PR for this?

**Comment by albfan** [comment]
done. https://github.com/MaksymBilenko/docker-oracle-12c/pull/44

**Comment by MaksymBilenko** [comment]
Merged #44

**Comment by MaksymBilenko** [comment]
@albfan Could you please close issue once verified

**Comment by albfan** [comment]
I already use it to import a dump so this is working.
