### ISSUE TITLE
Avoid to use volume for oracle

### ISSUE THREAD

**Issue by albfan** [MaksymBilenko/docker-oracle-12c#43]
If you remove 

    VOLUME ["/u01/app/oracle"]

from Dockerfile, it will be not mounted by default (empty) so you can have static databases

1) Import a dump
2) save a tag with `docker commit`
3) Share image tagged for CI, testing, etc...

https://github.com/albfan/docker-oracle-12c/commit/3a9a3b5327a96d695a6a7fad1e7991b88e83945f

**Comment by MaksymBilenko** [comment]
@albfan there was some issues on different platforms. Could you please play around Dockerfile/VOLUME and test it on Windows/Mac/Linux?
Thank you

**Comment by MaksymBilenko** [comment]
@albfan it makes sense...

**Comment by albfan** [comment]
Sure, I can report feedback for Windows/Linux

**Comment by albfan** [comment]
Windows working correctly. I think that's enough to test this.

The only concern is to clearly document how to use existing databases with volume, but README is well documented

**Comment by albfan** [comment]
Just seen: https://github.com/MaksymBilenko/docker-oracle-12c/commit/4dd6591b811f0da5b47b01f927adcfb02f5484dd

**Comment by filippetrovic** [comment]
But now we can not configure this volume from Kitematic.
Can we make some compromise solution?

**Comment by albfan** [comment]
Opps! https://github.com/docker/kitematic/issues/1923.

@filippetrovic add a volume because a third party app does not work without it seems wrong. You can always extend this dockerfile to have your volume but that's only a workaround for kitematic (someone needs to implement an add volume)

**Comment by filippetrovic** [comment]
Same thoughts here.
But I'm not sure what is semantic of VOLUME keyword in Dockerfile.
However, I do not insist on reverting this change.
