### ISSUE TITLE
entrypoint.sh

### ISSUE THREAD

**Issue by neilblue** [MaksymBilenko/docker-oracle-12c#45]
In the entrypoint.sh script should the line:

chown 664 /etc/oratab

read:

chmod 664 /etc/oratab

Thanks

**Comment by MaksymBilenko** [comment]
@neilblue what is it for? is it causing some issues?

**Comment by ChaosEngine** [comment]
man chmod. In general it's bad syntax.

**Comment by neilblue** [comment]
the two lines:
chown oracle:dba /etc/oratab
chown 664 /etc/oratab
just look like the second one was ment to be chmod. I am not familiar with oracle installs.

**Comment by neilblue** [comment]
Thank you for putting this container together. I am in the process of trying to initialise the database during container creation to I can start a fresh container quickly with a clean instance.
