### ISSUE TITLE
Error connecting to database from application: ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by tjheslin1** [MaksymBilenko/docker-oracle-12c#48]
I'm trying to connect to the oracle container in a golang project:

I'm using the connection string: "_system/oracle@172.0.0.1:1521/xe.oracle.docker_".

Note: If I replace "172.0.0.1" with "localhost" I get ORA-21561: OID generation failed.

Here are the logs of my database starting up using the command: "_docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c_":

        Database not initialized. Initializing database.
        Starting tnslsnr
        Copying database files
        1% complete
        3% complete
        11% complete
        18% complete
        26% complete
        37% complete
        Creating and starting Oracle instance
        40% complete
        45% complete
        50% complete
        55% complete
        56% complete
        60% complete
        62% complete
        Completing Database Creation
        66% complete
        70% complete
        73% complete
        85% complete
        96% complete
        100% complete
        Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
        Configuring Apex console
        Database initialized. Please visit http://#containeer:8080/em http://#containeer:8080/apex for extra configuration if needed
        Starting web management console

        PL/SQL procedure successfully completed.

        Starting import from '/docker-entrypoint-initdb.d':
        found file /docker-entrypoint-initdb.d//docker-entrypoint-initdb.d/*
        [IMPORT] /entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

        Import finished

        Database ready to use. Enjoy! ;)

I'm attempting to connect using the following line in go: 

    db, err := sql.Open("oci8", "system/oracle@172.0.0.1:1521/xe.oracle.docker")

The application _panic_ s which is a golang construct akin to throwing an uncaught exception and I get the following error message:
    ORA-12541: TNS:no listener

Unfortunately this is the only error message I get. No more detail.

Googling this suggests editing a file called`tnsnames.ora `. I can't see this anywhere in the image.
Issue #14 mentions this file but was closed without any further comments.

Note: I am using the following oracle sql drive for Go: https://github.com/mattn/go-oci8. This project has an issue which references this oracle error message but I can't get any help from it:
https://github.com/mattn/go-oci8/issues/147. As mentioned in the issue, I am doing a `db.Ping()` which is the point at which I get the error.

**Comment by Glavin001** [comment]
@tjheslin1 did you end up figuring out a solution to this problem?

**Comment by tjheslin1** [comment]
@Glavin001 Unfortunately not. As the project I'm working on is needed soon I'm instead working on a Java implementation. Still using the oracle container but with JDBC which I have more experience in.

I will have to spend more time with the oracle sql driver for Golang which appears to need more work to be more usable.
