### ISSUE TITLE
How to create light weight empty database

### ISSUE THREAD

**Issue by ttw19974** [MaksymBilenko/docker-oracle-12c#5]
How do I modify the script to create empty database

pretty much I am trying to run docker image faster with empty database, then I will run a sql script to create my tables ..etc.

**Comment by MaksymBilenko** [comment]
Hello,
Database creation is in this line ant entrypoint.sh
```			su oracle -c "$ORACLE_HOME/bin/dbca -silent -createDatabase -templateName General_Purpose.dbc -gdbname xe.oracle.docker -sid xe -responseFile NO_VALUE -characterSet AL32UTF8 -totalMemory $DBCA_TOTAL_MEMORY -emConfiguration LOCAL -pdbAdminPassword oracle -sysPassword oracle -systemPassword oracle"
```
If you would be able to play around with this one and suggest what parameters could be moved out to be configurable - would be very nice

Cheers
