### ISSUE TITLE
SYS password

### ISSUE THREAD

**Issue by qrtega** [MaksymBilenko/docker-oracle-12c#50]
Dear @MaksymBilenko,

After start the container and connect succesfully to the database as SYSTEM with password "oracle", i try to connect as SYS user with the same password as SYSTEM, but i can't access. It seems that the password is not "oracle".

Could you help me?

**Comment by MaksymBilenko** [comment]
Have you tried `as sysdba`?

**Comment by qrtega** [comment]
Yes, I tried it

**Comment by MaksymBilenko** [comment]
should work, here is DBCA from entrypoint.sh `-pdbAdminPassword oracle -sysPassword oracle -systemPassword oracle`
