### ISSUE TITLE
Unable to increase processes in oracle 12 c docker

### ISSUE THREAD

**Issue by pavan2017** [MaksymBilenko/docker-oracle-12c#51]
Am trying to increase processes for oracle 12 c.But i get the following exception
SQL> show parameter processes;

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
aq_tm_processes                      integer     1
db_writer_processes                  integer     1
gcs_server_processes                 integer     0
global_txn_processes                 integer     1
job_queue_processes                  integer     1000
log_archive_max_processes            integer     4
processes                            integer     300
SQL> alter system set processes=500 scope=spfile;
alter system set processes=500 scope=spfile
*
ERROR at line 1:
ORA-65040: operation not allowed from within a pluggable database

**Comment by MaksymBilenko** [comment]
try to shudown database firts and then set parameters and then `startup;`

**Comment by MaksymBilenko** [comment]
```
SQL> alter system set processes=500 scope=spfile;

System altered.

SQL> alter system set sessions=555 scope=spfile;

System altered.

SQL> alter system set transactions=610 scope=spfile;

System altered.
```

**Comment by MaksymBilenko** [comment]
```
SQL> alter system set processes=500 scope=spfile;

System altered.

SQL> alter system set sessions=555 scope=spfile;

System altered.

SQL> alter system set transactions=610 scope=spfile;

System altered.
```

**Comment by greeshmakr** [comment]
Hi, I am also getting the same error, when trying to set the processes in Oracle 18c (Pluggable Database). Tried after shutdown and startup too.

SQL> show con_name;

CON_NAME
------------------------------
XEPDB1
SQL> shutdown immediate;
Pluggable Database closed.
SQL> alter system set processes=500 scope=spfile;
alter system set processes=500 scope=spfile
*
ERROR at line 1:
ORA-65040: operation not allowed from within a pluggable database


SQL> startup;
Pluggable Database opened.

**Comment by greeshmakr** [comment]
@MaksymBilenko  Hi, I am also getting the same error, when trying to set the processes in Oracle 18c (Pluggable Database). Tried after shutdown and startup too.

SQL> show con_name;

CON_NAME
- - - - - - - - -

XEPDB1
SQL> shutdown immediate;
Pluggable Database closed.
SQL> alter system set processes=500 scope=spfile;
alter system set processes=500 scope=spfile
*
ERROR at line 1:
ORA-65040: operation not allowed from within a pluggable database

SQL> startup;
Pluggable Database opened.
