### ISSUE TITLE
Error importing dump

### ISSUE THREAD

**Issue by amitisgenius** [MaksymBilenko/docker-oracle-12c#52]
I am trying to import a dump when starting a new instance.
docker run -d -e IMPORT_FROM_VOLUME=true -p 1522:1521 -v /home/ssin/workspace/oracle_data:/u01/app/oracle sath89/oracle-12c

Error in the logs is 
chown: changing ownership of '/u01/app/oracle/mydb.dmp': Operation not permitted
chown: changing ownership of '/u01/app/oracle': Operation not permitted

Please suggest on what I might be doing wrong. I am very new to Docker so I might be missing something very basic.

**Comment by MaksymBilenko** [comment]
Check file permissions
