### ISSUE TITLE
No UTF 8 with MacOS

### ISSUE THREAD

**Issue by areyouready** [MaksymBilenko/docker-oracle-12c#53]
When I start the image on MacOS the database is always created with the WE8MSWIN1252 encoding. Is there a way to install it with UTF8?

**Comment by MaksymBilenko** [comment]
I'll try to find some way to deal with it

**Comment by MaksymBilenko** [comment]
@areyouready you can run this:
`docker run -d -p 8080:8080 -p 1521:1521 -p 6800:6800 -e MANUAL_DBCA=true -e VNC_PASSWORD=passwd sath89/oracle-12c`
instead of automated database initialization you can go to the http://localhost:6800 and configure it manually
Please update this issue with any news

**Comment by junjianw** [comment]
@MaksymBilenko 

i create it successful，but  when after docker restart, database startup fail 
```
docker run -d -p 9702:8080 -p 1521:1521 -p 6800:6800 -v /work/oracle/12c_novnc:/u01/app/oracle -m 4g -e MANUAL_DBCA=true -e VNC_PASSWORD=1234 sath89/oracle-12c:novnc

```
 the logs

```
found files in /u01/app/oracle/oradata Using them instead of initial database
ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/u01/app/oracle/product/12.1.0/xe/dbs/initxe.ora'
Starting web management console
BEGIN DBMS_XDB.sethttpport(8080); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)

```
