### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by christianbundy** [MaksymBilenko/docker-oracle-12c#58]
Hey there,

It looks like your most recent change to `xe` is a breaking change, but when we make the change in our codebase we don't have an easy way to codify the fact that other team members need to download the newest image to have it work. Would you mind moving to semver (or similar) so that we can resolve this problem in the future?

Thanks for your work on this project!

**Comment by Glavin001** [comment]
Our team experienced this problem, as well. Fortunately, one of our team members took a look back at this and discovered the breaking change.

**Comment by MaksymBilenko** [comment]
Sorry for that... But I thaink that XE by default would be most useful..

**Comment by christianbundy** [comment]
I agree, and I appreciate the move to `xe`, but I'd love some sort of versioning system so that we know when breaking changes are coming. Would you be open to using something like [semantic versioning](http://semver.org/)? Thanks @MaksymBilenko!
