### ISSUE TITLE
Docker-compose: Oracle container could not start after stop

### ISSUE THREAD

**Issue by chinkung** [MaksymBilenko/docker-oracle-12c#59]
I see this error after docker stop and start again and oracle did not start (run docker-compose as root user on centos 7)

```
# docker -v
Docker version 17.06.0-ce, build 02c1d87
# docker-compose -v
docker-compose version 1.15.0, build e12f3b9
```

```
# docker-compose stop
# docker-compose up -d
# docker-compose logs -f
```

**found files in /u01/app/oracle/oradata Using them instead of initial database
rm: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty**

Here is my docker-compose.yml
> oracle:
>     image: sath89/oracle-12c
>     container_name: oracle
>     restart: always
>     environment:
>       - CHARACTER_SET=TH8TISASCII
>     ports:
>       - 1521:1521
>     volumes:
>       - ./database:/u01/app/oracle
>       - /etc/localtime:/etc/localtime:ro

**Comment by chinkung** [comment]
I also found this error on database recreation, Is this normal ?

Database not initialized. Initializing database.
**mv: cannot remove '/u01/app/oracle-product/12.1.0/xe/dbs': Directory not empty**
Starting tnslsnr
Copying database files
1% complete
3% complete
11% complete
18% complete
37% complete
Creating and starting Oracle instance

**Comment by chinkung** [comment]
Seem to be a problem with Overlay on CentoOS 7 

https://github.com/moby/moby/issues/10294

**Comment by MaksymBilenko** [comment]
Hi,
Had similar problem on Centos 7.3
Check `/usr/lib/systemd/system/docker.service` and modify storage driver:
`ExecStart=/usr/bin/dockerd -s devicemapper -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock`
Solved that issue for me.

**Comment by chinkung** [comment]
The problem is they are not recommend to use [loop-lvm on production](https://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/).

https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

Finally, we might need to setup [direct-lvm mode](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production) or [recreate filesystem using -n ftype=1](https://linuxer.pro/2017/03/what-is-d_type-and-why-docker-overlayfs-need-it/) to solve this problem.

**Comment by MaksymBilenko** [comment]
Closing this issue because its not related to this image
