### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mrts** [MaksymBilenko/docker-oracle-12c#6]
It's a bit weird to express gratitude with an issue, please feel free to close this :).

But I want to really thank you for making this image available. It works really well and saves a lot of unnecessary pain and trouble from setting up the development environment.

**Comment by MaksymBilenko** [comment]
Cool, thanks for the feedback :+1:

**Comment by msmitherdc** [comment]
I wanted to say the same thing. This has been extremely helpful to me and saved a lot of time setting up an instance for our Jenkins CI testing.

**Comment by MaksymBilenko** [comment]
@msmitherdc  :+1:
