### ISSUE TITLE
Database creation not using AL32UTF8 by default

### ISSUE THREAD

**Issue by ball6847** [MaksymBilenko/docker-oracle-12c#64]
I have to explicitly set  `CHARACTER_SET=AL32UTF8`  to make the container bootstrap with `AL32UTF8` char set.
I think it should pick `AL32UTF8` by default if `$CHARACTER_SET` is not defined.

the corresponding line - https://github.com/MaksymBilenko/docker-oracle-12c/blob/e6b02c8b7fa378a3110d4e2867cae7053735493f/entrypoint.sh#L14

Is dollar sign missing from expression ?

**Comment by MaksymBilenko** [comment]
Yes, you are right!
Thanks for a note

**Comment by lizhouyang** [comment]
when i use CHARACTER_SET  
`docker run -it --rm -p 8080:8080 -p 1521:1521 -v /root/oracle-docker:/u01/app/oracle sath89/oracle-12c  CHARACTER_SET=ZHS16GBK`  
it return `Database is not configured. Please run '/entrypoint.sh' if needed.
/entrypoint.sh: line 133: exec: CHARACTER_SET=ZHS16GBK: not found
` 
so, what should i do? thanks~

**Comment by MaksymBilenko** [comment]
Instead of `docker run -it --rm -p 8080:8080 -p 1521:1521 -v /root/oracle-docker:/u01/app/oracle sath89/oracle-12c CHARACTER_SET=ZHS16GBK`
try to `docker run -it --rm -p 8080:8080 -p 1521:1521 -v /root/oracle-docker:/u01/app/oracle 
-e CHARACTER_SET=ZHS16GBK sath89/oracle-12c`
