### ISSUE TITLE
Container restarted with -v, but no database from prior start

### ISSUE THREAD

**Issue by mangelo123** [MaksymBilenko/docker-oracle-12c#65]
Here is the command:

docker run -d -p 8080:8080 -p 1521:1521 -v /Users/MAngelo/oracle-forecast:/u01/app/oracle  --name oracle sath89/oracle-12c

I spent hours setting up good test data. Had to reboot my computer. After running the command above, I am not seeing my previous database.

**Comment by anilsamuel** [comment]
What are the contents of /Users/MAngelo/oracle-forecast ?

**Comment by mangelo123** [comment]
It is the same contents that the previous docker container created. I just rebooted my machine and when I tried to restart the container, the db is gone. The contents are still there. It just does not seem to be using the external directory.

**Comment by mangelo123** [comment]
What's the status of this? Is this fixed or could you not recreate it?

**Comment by MaksymBilenko** [comment]
Unable to reproduce this issue
