### ISSUE TITLE
Upgrade to r2 or create separate tag

### ISSUE THREAD

**Issue by milosonator** [MaksymBilenko/docker-oracle-12c#67]
It would be awesome if you could do a build for `r2` and add it as a tag. I'm not sure if you want to move this image to that build eventually, but definitely something to consider.

**Comment by MaksymBilenko** [comment]
Not sure that I would have a time for this in close future.
I suggest to take a look on official oracle db image in docker store

**Comment by MaksymBilenko** [comment]
https://github.com/MaksymBilenko/docker-oracle-12c/issues/78
