### ISSUE TITLE
There is some way to configure for system and sys users to have remote access?

### ISSUE THREAD

**Issue by jmoraxoftix** [MaksymBilenko/docker-oracle-12c#69]
There is some way to configure for system and sys users to have remote access?

I was reviewing the image and the work you have done is very interesting. But I could not give to configure remote access of the users sys and system, any comment about it?

Thanks

**Comment by RealKanashii** [comment]
If your host has the 1521 port open you can connect from everywhere. Change the connection attributes "localhost" by your host IP (no container IP).
