### ISSUE TITLE
Remote connect to Oracle

### ISSUE THREAD

**Issue by ferdyh** [MaksymBilenko/docker-oracle-12c#7]
I'm trying to connect to the Oracle 12c instance created using the docker image. Command i ran:

`docker run -d -p 8080:8080 -p 1521:1521 pengbai/docker-oracle-12c-r1`

The image runs on a Digital Ocean VM. When i try to connect using SQLDeveloper i get the following error:

> Status: Failure -Test failed: IO-error: The Network Adapter could not establish the connection

From my experience, this usually has to do with the hostname settings. Any way to resolve this?

**Comment by ferdyh** [comment]
My bad... Company firewall... Perfect docker image!

**Comment by MaksymBilenko** [comment]
@ferdyh I was just about to look into that, thank you for the update
