### ISSUE TITLE
Update Oracle version to 12.2

### ISSUE THREAD

**Issue by roooodcastro** [MaksymBilenko/docker-oracle-12c#78]
Hello, I run your awesome Oracle image for my test environment.

When I run `SELECT * FROM V$VERSION;`, I get the following result:

    Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

However, my actual production Oracle DB is running

    Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production

[Turns out that starting from 12.2, identifier names can have up to 128 characters](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/newft/new-features.html#GUID-64283AD6-0939-47B0-856E-5E9255D7246B), instead of only 30, which was the limit until 12.1. This prevents me from testing some new tables and columns, which have names longer than 30 characters.

Is it possible to upgrade the base Oracle version to 12.2? I tried upgrading the image in Rancher (I set it up as `sath89/oracle-12c:latest`), but nothing happeneed, leading mt to believe the latest version of the image is actually 12.1.

**Comment by MaksymBilenko** [comment]
Have you tried this one?
https://hub.docker.com/r/sath89/oracle-ee-12c/

**Comment by roooodcastro** [comment]
Sorry, forgot to answer. I didn't try the EE version as we have decided to just shorten the identifiers to make them fit the 30 characters rule.

However, for future reference, if I have an existing Oracle installation (with many users, configurations, schemas, etc), can I simply switch to the EE version while pointing to the same data directory? Will that work?

**Comment by MaksymBilenko** [comment]
I think that you would need to run some migrations.
Reffer to official oracle docs

**Comment by roooodcastro** [comment]
Thank you. As it's only for testing, I don't think it's actually worth the effort, so I will keep using the 30 char limit.
