### ISSUE TITLE
reset password for APEX ADMIN

### ISSUE THREAD

**Issue by ch-guo** [MaksymBilenko/docker-oracle-12c#79]
Hi,

just have a question about upgraded APEX, where would I find the APEX code of the (downloaded) upgrade version?

I would like to reset password for APEX ADMIN on INTERNAL Workspace (the default password is no more works, don't know why, whatever...)

After I run the apxchpwd.sql under /u01/app/oracle-product/12.1.0/xe/apex/, all seem ok, but Login said, that user ADMIN is locked. I searched in Web, it could because I've already upgraded the APEX, the APEX 5.0 was installed and the apex/ here is the old version.

Therefore I'd like know where could I find the APEX for the upgraded APEX in this docker?

Thank you very much for the help!
Christian

**Comment by MaksymBilenko** [comment]
Run apex container linked to the database with bash session and reset password manually from apex folder
