### ISSUE TITLE
Container Database

### ISSUE THREAD

**Issue by drewwells** [MaksymBilenko/docker-oracle-12c#8]
12c introduced multitenant which is available when started as a container DB. Is it possible to start this as a container db. If so, is it documented anywhere?

**Comment by drewwells** [comment]
Well haven't gotten very far on this. To enable containerDatabase, add `-createAsContainerDatabase true` [diff](https://gist.github.com/drewwells/93401d4361336df6cec6).

However, the database initialization usually fails. I increased shared memory to avoid one error, but it is still failing to startup.

`docker run --shm-size=1024MB -p 8080:8080 -p 1521:1521 -v /tmp/oracle:/u01/app/oracle oracle-cdb`

**Comment by MaksymBilenko** [comment]
Hi @drewwells I'll take a look once I'll have a time for this
Cheers

**Comment by drewwells** [comment]
Thanks @MaksymBilenko here's the output of trace: https://gist.github.com/drewwells/5d7c337e85d563b538fd

**Comment by MaksymBilenko** [comment]
@drewwells Sorry, for now don't have time for this.
I'll keep this issue open and I'll take a look at this when I would have some time.
If you do need this functionality - you can play around database creation parameters and post here some suggestions and tweaks
Cheers
