### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by anushibin007** [MaksymBilenko/docker-oracle-12c#80]
I get this error when trying to run the image:

docker: Error response from daemon: mkdir /var/lib/docker/overlay/e5bf7a446b70af0d912845315c394070ff8f829d2d82295ceb9a796d4bb6fda3-init/merged/dev/shm: invalid argument.

This is the command I passed:
docker run -td --privileged -p 8080:8080 -p 1521:1521 --name oracle_container sath89/oracle-12c

**Comment by fadc80** [comment]
I had the same problem on centos 7.1 docker 18.03.0-ce.

**Comment by MaksymBilenko** [comment]
This is centos kernel issue with docker's default storage driver.
Try to switch to overlayfs

**Comment by fadc80** [comment]
I found this [workaround](https://stackoverflow.com/questions/42248571/cannt-run-or-build-docker-images-on-centos-7).
