### ISSUE TITLE
importing sql file

### ISSUE THREAD

**Issue by drewjocham** [MaksymBilenko/docker-oracle-12c#86]
Thank very much for doing this. I have tried for two days now to import a SQL file to 1) create the tables and 2) init the database. Everything I try doesn't seem to work. Have you done this before? If so how did you accomplish it?

**Comment by MaksymBilenko** [comment]
This image in use by many people and I'm personally imported ten's of dump's on it.
Maybe you missing REMAP SCHEME or something like this?
