### ISSUE TITLE
cp: cannot stat '/docker-entrypoint-initdb.d/*': No such file or directory

### ISSUE THREAD

**Issue by florianpnt** [MaksymBilenko/docker-oracle-12c#88]
Hi there,

I was trying to set up an oracle database for development purposes.
Unfortunately on my PC as well as on every colleague's PC we get the error:

`cp: cannot stat '/docker-entrypoint-initdb.d/*': No such file or directory`

It seems to have be connected to the changes added about 20 hours ago.

**Comment by MaksymBilenko** [comment]
Reverted this PR.
Please check 30 minutes later

**Comment by florianpnt** [comment]
THanks for the quick reaction :)

**Comment by MaksymBilenko** [comment]
Np,
Just leave a feedback on statues after this revert

**Comment by florianpnt** [comment]
Thanks it's starting again!
