### ISSUE TITLE
install another database in the docker image

### ISSUE THREAD

**Issue by mehrandowlatshahi** [MaksymBilenko/docker-oracle-12c#9]
Hi There

Thank you for the docker image you have provided.
Can you please explain how I could install another database for which I have an oracle dump file?

Thank you in advance for your help.

Best Regards

Mehran
Sydney, Australia

**Comment by ChaosEngine** [comment]
use docker volume mount to mount dump file and than put it into:
/u01/app/oracle/admin/xe/dpdump/

and proceed as usual, impdp, or someother way of executing data pump import

**Comment by mehrandowlatshahi** [comment]
Many thanks for your hints on this.

Best Regards
Mehran
