### ISSUE TITLE
Took more than 1 hour to start up and didn't complete

### ISSUE THREAD

**Issue by carlos-algms** [MaksymBilenko/docker-oracle-12c#90]
I've downloaded the the image today and ran the suggested command:

```shell
docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c
```

I have been passed more than 1 hour and it still on 85%.

Is that normal?

**Comment by artnaseef** [comment]
One hour is high.  I'm seeing 10 minute startup times here.

Does the system running the container have adequate resources?  If the system is low on memory or cpu resources, that could explain the extra slow startup.
