### ISSUE TITLE
Can you add a way to configure sid

### ISSUE THREAD

**Issue by Dhananjay-J-P** [MaksymBilenko/docker-oracle-12c#92]
Can you please add a way to configure sid?

**Comment by MaksymBilenko** [comment]
You can do this by using image with VNC and init database manually

**Comment by Dhananjay-J-P** [comment]
Can you please tell me how to do that I tried logging into container and execute command but could not see any input. I also tried to execute dbca with following command but getting error.

Command
`docker exec conatainer-1 /bin/bash -H -u oracle -c "export DISPLAY=192.168.1.187:1 && dbca"`

Error: 
`/u01/app/oracle/product/12.1.0/xe/bin/oracle: /u01/app/oracle/product/12.1.0/xe/bin/oracle: cannot execute binary file`
