### ISSUE TITLE
ath89/oracle-12c images not downloaded 

### ISSUE THREAD

**Issue by tusharjadhav2986** [MaksymBilenko/docker-oracle-12c#98]
we are trying to download sath89/oracle-12c images but we get unauthorized authentication required error, 
 i have login docker then try to pull image. 
kindly find attached screen shot
![oracke db](https://user-images.githubusercontent.com/37026843/41024372-b0428b10-698c-11e8-85c7-f94d8d835981.JPG)
 
Please guide us

**Comment by ttecles** [comment]
I could download without any problem

**Comment by MaksymBilenko** [comment]
Looks like some glitch of docker hub or you using some proxy
