### ISSUE TITLE
where is the setting file in the images?

### ISSUE THREAD

**Issue by TedWithAHammer** [MaksymBilenko/docker-oracle-12c#99]
i just get ora-12505 error
i can login the db in the container with docker exec -it sath89/oracle-12c /bin/bash
here is the docker logs 
Database not initialized. Initializing database.
Starting tnslsnr
Copying database files
1% complete
3% complete
11% complete
18% complete
26% complete
37% complete
Creating and starting Oracle instance
^@40% complete
45% complete
^@^@50% complete
55% complete
56% complete
60% complete
62% complete
Completing Database Creation
66% complete
70% complete
73% complete
85% complete
^@96% complete
100% complete
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
Configuring Apex console
^@Database initialized. Please visit http://#containeer:8080/em http://#containeer:8080/apex for extra configuration if needed
Starting web management console

PL/SQL procedure successfully completed.

Starting import from '/docker-entrypoint-initdb.d':
ls: cannot access /docker-entrypoint-initdb.d/*: No such file or directory
Import finished

Database ready to use. Enjoy! ;)

sqlplus system/oracl
![image](https://user-images.githubusercontent.com/9396361/41042363-0ec358b2-69d4-11e8-9d9b-24a4fdc1ed03.png)
![image](https://user-images.githubusercontent.com/9396361/41042751-01ce07fa-69d5-11e8-9e74-11a538d105c5.png)

my /data/diag/tnslsnr/bfa6b6394570/listener/alert/log.xml
<msg time='2018-06-06T13:50:54.074+00:00' org_id='oracle' comp_id='tnslsnr'
 type='UNKNOWN' level='16' host_id='bfa6b6394570'
 host_addr='172.17.0.2'>
 <txt>06-JUN-2018 13:50:54 * service_update * xe * 0
 </txt>
</msg>
<msg time='2018-06-06T13:51:24.105+00:00' org_id='oracle' comp_id='tnslsnr'
 type='UNKNOWN' level='16' host_id='bfa6b6394570'
 host_addr='172.17.0.2'>
 <txt>06-JUN-2018 13:51:24 * service_update * xe * 0
 </txt>
</msg>
root@bfa6b6394570:~# tnsping localhost:1521/xe

TNS Ping Utility for Linux: Version 12.1.0.2.0 - Production on 06-JUN-2018 14:07:39

Copyright (c) 1997, 2014, Oracle.  All rights reserved.

Used parameter files:

Used HOSTNAME adapter to resolve the alias
Attempting to contact (DESCRIPTION=(CONNECT_DATA=(SERVICE_NAME=xe))(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))
OK (0 msec)
root@bfa6b6394570:/# echo $ORACLE_HOME
/u01/app/oracle/product/12.1.0/xe
in this directory i can not find the tnsnames.ora,so i have no clue to solve this problem ,need any furthur infomation?
this is my first time to use oracle...

**Comment by TedWithAHammer** [comment]
could offer me a clue,how to locate the problem ?a little hurry,thxs

**Comment by MaksymBilenko** [comment]
Not sure, I think that you should refer to Oracle's documentation
